### ISSUE TITLE
Named IN parameters

### ISSUE THREAD

**Issue by root-talis** [vsch/kotlin-jdbc#1]
It would be great to make automatic unwrapping of named IN parameters based on their count as such:

```
// this
sqlQuery(
    "SELECT * FROM foo WHERE id IN(:ids) AND type = :type",
    mapOf(
        "ids" to setOf(1, 2, 3),
        "type" to "bar"
    )
)

// to this
"SELECT * FROM foo WHERE id IN(?, ?, ?) AND type = ?"
```

I'm ready to help with this task if you approve it.

**Comment by vsch** [comment]
@root-talis, that is a great idea. It should be reasonably easy to add this based on the parameter being of a collection type.

If you want please go ahead and it. PRs are welcome.

I updated the repo for 0.3.2 and did a maven update.

**Comment by vsch** [comment]
@root-talis, did you get a chance to start on this? I took a look at the code and saw that it required some refactoring of the `sqlCall` and `sqlQuery` implementation to be able to handle detection of parameter type since original code evaluates substitutions before parameters are assigned.

I have an initial implementation and if you have not done this yet then I will update the latest code changes and save you the hassle of having to implement it. 

BTW, comments and suggestion on the implementation are welcome. I only get to use the library now for proof of concept and playing with ideas not real production environment. So my insight into real applications is limited at the moment.

I originally wrote it hoping to convince a client to switch development from Play/Scala/Slick to Spring Boot/Kotlin/kotlin-jdbc for a project that was going from proof of concept into development. Even though they liked the simplicity and transparency to actual SQL, they felt committed to the Play/Scala/Slick choice which is unusable for moderate to high complexity queries and you can forget about trying to use query plans to optimize your database.

**Comment by vsch** [comment]
@root-talis, having looked a bit more at this I realized that it has a lot of implications.

I also realized that Model implementation uses hard coded back quote quoting of identifier.

These are now removed, with default not quoting identifiers. 

If quoting is desired, I added configuration via `Model.databaseQuoting` property, with function arguments and constructor arguments added for quoting since a model may need to use different quoting based on the database session. I am not happy with this kludge but it should only be needed rarely. Most of the time no quoting or the same quoting should be enough.

I am going to update the repo and make a new release. 

There are some changes to ModelCompanion and model implementation to handle the optional quote argument. 

Kotlin model generation groovy script updated so it can be used to generate a model and see what differences need to be applied to previous model source (if auto generated cannot be used as is).

**Comment by root-talis** [comment]
@vsch, I haven't had time do start on this yet, and I was planning to work on this task on this weekend (August 8 and 9). Thanks for the heads up! I will pull the changes from version 0.4.0 into my repo and work on that. My plan was to scrap together a prototype and then show it to you for code review before making a pull request.

I am yet unfamiliar with details of design of kotlin-jdbc, so at this point I cannot suggest any other changes.
